version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  db:
    image: postgres:15
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      - POSTGRES_USER=vexaradmin
      - POSTGRES_PASSWORD=V3xar@2024!Prod
      - POSTGRES_DB=vexar_fleet
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
