# The DB admin password is generated by Terraform (random_password) rather
# than supplied as a variable, specifically so it never needs to exist in
# a .tfvars file, CI secret, or anyone's shell history. It's written
# directly into Key Vault (see keyvault.tf) and read by the app from
# there via managed identity - Terraform state itself will contain it in
# plaintext, which is exactly why remote state (providers.tf) must be
# encrypted-at-rest storage with access restricted to the pipeline
# identity, not a shared/local state file in a real deployment.
resource "random_password" "postgres_admin" {
  length      = 32
  special     = true
  min_upper   = 2
  min_lower   = 2
  min_numeric = 2
  # Restrict special characters to ones Postgres/connection strings handle
  # cleanly, avoiding characters that need URL-encoding in a connection URI.
  override_special = "-_="
}

resource "azurerm_postgresql_flexible_server" "main" {
  name                = "${local.name_prefix}-psql"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location

  version    = var.postgres_version
  sku_name   = var.postgres_sku
  storage_mb = var.postgres_storage_mb

  administrator_login    = var.postgres_admin_username
  administrator_password = random_password.postgres_admin.result

  # Private access only - no public_network_access_enabled, no firewall
  # rules opening it to the internet. This is the single most important
  # network control in the whole design (see network.tf comment).
  delegated_subnet_id = azurerm_subnet.postgres.id
  private_dns_zone_id = azurerm_private_dns_zone.postgres.id

  backup_retention_days        = var.environment == "prod" ? 30 : 7
  geo_redundant_backup_enabled = var.environment == "prod"

  # High availability doubles cost (a synchronous standby replica) - only
  # justified once this is carrying real production fleet traffic. See
  # docs/REPORT.md, Deliverable 5, for how this evolves with scale.
  dynamic "high_availability" {
    for_each = var.environment == "prod" ? [1] : []
    content {
      mode = "ZoneRedundant"
    }
  }

  depends_on = [azurerm_private_dns_zone_virtual_network_link.postgres]

  tags = local.tags

  lifecycle {
    # Prevents Terraform from wanting to recreate the server (a
    # destructive, downtime-causing operation) just because the
    # generated password rotates on some future apply - password rotation
    # should be a deliberate, separate action (see docs/REPORT.md,
    # Deliverable 5, access control section), not an accidental side
    # effect of an unrelated `terraform apply`.
    ignore_changes = [administrator_password]
  }
}

resource "azurerm_postgresql_flexible_server_database" "app" {
  name      = "vexar_fleet"
  server_id = azurerm_postgresql_flexible_server.main.id
  collation = "en_US.utf8"
  charset   = "UTF8"
}

# Reasonable production defaults - see docs/REPORT.md Deliverable 5 for
# the full connection-management/pooling discussion (this is the
# server-side counterpart to the app's own connection pool in src/db.js).
resource "azurerm_postgresql_flexible_server_configuration" "max_connections" {
  name      = "max_connections"
  server_id = azurerm_postgresql_flexible_server.main.id
  # Burstable B1ms defaults to a low ceiling; raised modestly since the
  # app pool is sized at 10 per replica and this may run multiple replicas.
  value = "100"
}
